name: real-time-trades-tracker
services:
  # TODO: Implement when ready to publish
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - ASPNETCORE_URLS=http://+80
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DatabaseConnectionString=Host=postgres;username=admin;password=123456789;database=postgres_db;TrustServerCertificate=True;
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:18.3-bookworm
    container_name: postgres_db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: real_time_trades_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
