name: real-time-trades-tracker
services:
  postgres:
    image: postgres:18.3-bookworm
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: real-time-trades-tracker-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
